// Drill "banter" — the ONE model call in this app, and it is LOCAL ONLY by design. Anti-Tank is
// deliberately KEYLESS: there is no Claude code path and no ANTHROPIC_API_KEY (prep-pack content
// is generated by Claude Code in the terminal and imported via /api/opportunities/:id/pack).
// The qwen3 endpoints (primary + fallback) come from commander/src/ai.js; a dead endpoint makes
// generateBanter resolve to null so the drill just carries on without pushback.

// qwen3 emits chain-of-thought inside <think>…</think>; strip it (and any stray/unclosed tag) so
// only the answer is used. Paired with the "/no_think" directive, which tells qwen3 to skip it.
const stripThink = (t) =>
  String(t)
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    .replace(/<\/?think>/gi, '')
    .trim();

async function callLocal({ system, user, maxTokens = 220 }) {
  const body = {
    model: process.env.LOCAL_LLM_MODEL || undefined,
    messages: [
      { role: 'system', content: `${system}\n/no_think` },
      { role: 'user', content: user },
    ],
    temperature: 0.6,
    max_tokens: maxTokens,
  };
  const endpoints = [process.env.LOCAL_LLM_URL, process.env.LOCAL_LLM_FALLBACK_URL].filter(Boolean);
  let lastErr;
  for (const url of endpoints) {
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 60000);
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: ctrl.signal,
      });
      clearTimeout(t);
      if (!res.ok) throw new Error(`LLM ${res.status}`);
      const data = await res.json();
      const text = stripThink(data?.choices?.[0]?.message?.content || '');
      if (text) return text;
      throw new Error('empty completion');
    } catch (err) {
      lastErr = err;
      console.warn(`[ai] local ${url} failed: ${err.message}`);
    }
  }
  throw lastErr || new Error('no local endpoint configured');
}

// One skeptical-interviewer follow-up for a drill card. Never throws: returns
// { text, provider: 'local' } or null (endpoint down / no endpoint configured).
export async function generateBanter({ company, role, question, my_answer, spoken_notes }) {
  const system = `You are a skeptical, senior interviewer at ${company || 'the company'} interviewing a candidate for ${role || 'a role'}. You just asked: "${question}". Reply with EXACTLY ONE tough but fair follow-up question that probes the weakest part of the candidate's answer — the thing a sharp interviewer would push on. One or two sentences, no preamble, no commentary, no markdown. Just the follow-up question.`;
  const user = spoken_notes?.trim()
    ? `The candidate answered (their own words):\n${spoken_notes}`
    : my_answer?.trim()
      ? `The candidate plans to answer with these talking points:\n${my_answer}`
      : `The candidate has not prepared an answer yet — ask the follow-up you'd use to probe an unprepared answer to the original question.`;
  try {
    const text = await callLocal({ system, user });
    return { text, provider: 'local' };
  } catch (err) {
    console.warn('[ai] banter failed:', err.message);
    return null;
  }
}
